# About the Author {-}

Dr. Timothy Anderson is the Department Chair of Engineering and Technology Management at Portland State University. He earned an Electrical Engineering degree from the University of Minnesota, as well as both  M.S. and Ph.D. degrees in Industrial Engineering from the Georgia Institute of Technology. Dr. Anderson has been the Program Chair or Co-Chair twenty times for PICMET, the Portland International Conference on the Management of Engineering and Technology since 1997. He leads the Extreme Technology Analytics research group.  He was President of Omega Rho, the International Honor Society for Operation Research.  With over 60 refereed publications, current research interests include analytics, benchmarking, technology forecasting, data mining, and new product development. He helped lead the creation of six graduate certificates at Portland State, including Business Intelligence and Analytics. 

Dr. Anderson is an enrolled member of the Pokagon Band of Potawatomi making him one of the few engineering department chairs in the country who is also a member of a Native American tribe. He values diversity and works to ensure that future engineers and scientists better represent the full community.  He has been recognized as a Sequoyah Fellow of the American Indian Science and Engineering Society. 
