# Nonlinear Programming

```{r Ch9setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(tidy = FALSE)
knitr::opts_chunk$set(cache = TRUE)
library (magrittr, quietly = TRUE) #Used for pipes/dplyr
library (dplyr, quietly = TRUE)
library (ROI, quietly = TRUE)
library (ROI.plugin.glpk, quietly = TRUE)
library (ROI.plugin.symphony, quietly = TRUE)
library (ompr, quietly = TRUE)
library (ompr.roi, quietly = TRUE)
library (pander, quietly = TRUE)
library (dplyr)
library (tint)  
library (tufte)
```

## Policies for Houselessness

To this point, we've constrained ourselves to the world of linear programming.  While many things applications can be modeled well using linear programming or linear approximations. \vspace{12pt}

Solving nonlinear problems is inherently challenging.  In general, you can think of some common nonlinear algorithms as being the equivalent of a very myopic (near-sighted) mountain climber searching for the highest peak. The climber is always in the immediate vicinity to move upwards until they can no longer go higher.  The variables could simply be x and y coordinates (or latitude and longitude) while the objective function is altitude.  
\vspace{12pt}

In Oregon, the highest peak found could vary greatly. If our very near-sighted climber started in downtown Portland, they might end on the top floor of a parking garage with an elevation of about 100 meters above sea level. With a little more luck, they might find their way to the West Hills with an elevation of about 350 meters. On the other hand, a searcher that started elsewehere in Oregon might end up on Mt. Hood with an elevation of over 3000 meters.  

A variety of tools can be used for solving nonlinear problems. This will be added to the chapter in the coming months.




